### ISSUE TITLE
When New Version !?!?!

### ISSUE THREAD

**Issue by jtlacci** [codfish/dotfiles#7]
The maintainers are slacking, really need to update for Mac changing default shells to zsh

**Comment by codfish** [comment]
https://github.com/codfish/dotfiles/wiki/Migrating-from-the-bash-dotfiles-to-the-new-Zsh-dotfiles

@jtlacci there you go. if you want to fork it, go for it and run

```sh
DOTFILES_REPO=jtlacci/dotfiles sh -c "$(curl -fsSL https://raw.githubusercontent.com/jtlacci/dotfiles/master/install.sh)"
```
